### ISSUE TITLE
build fails against pdm-pep517 1.0.5+

### ISSUE THREAD

**Issue by stanislavlevin** [bagel897/pytoolconfig#6]
With https://github.com/pdm-project/pdm-pep517/pull/120 the build fails:
```console
[builder@localhost pytoolconfig]$ python3 -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (pdm-pep517>=1.0.0)
* Getting dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/usr/lib/python3/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3/site-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/api.py", line 82, in build_sdist
    return Path(builder.build(sdist_directory)).name
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/sdist.py", line 60, in build
    version = self.meta_version
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/base.py", line 159, in meta_version
    meta_version = self.meta.version
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/base.py", line 154, in meta
    self._meta.validate(True)
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/metadata.py", line 58, in validate
    return validate_pep621(self.data, raising)
  File "/usr/src/tmp/build-env-vrxl922_/lib/python3/site-packages/pdm/pep517/validator.py", line 85, in validate_pep621
    raise PEP621ValidationError(validator.errors)
pdm.pep517.exceptions.PEP621ValidationError: {'license-expression': ['unknown field']}

ERROR Backend subprocess exited when trying to invoke build_sdist
```

`license-expression` has to be replaced with `license`.

**Comment by stanislavlevin** [comment]
Fixed in https://github.com/bagel897/pytoolconfig/commit/7fbd830f1c302ed8151ecc2bd52c40cf70b1a580.
